Text field
nightingale69/form.github.io pull request #3
Opened 2017-05-27 19:56 UTC by nightingale69

2017-06-26 10:02 UTC, AleksandrLv requested changes
У тебя проект запускается? Не должен, т.к. название файла с маленькой буквы, а в App.js импортируешь с большой. Все компоненты должны называться с большой буквы

2017-06-26 10:02 UTC, AleksandrLv commented on src/Components/form.js
> +            surname: "",
js одинарные кавычки, jsx двойные

2017-06-26 10:02 UTC, AleksandrLv commented on src/Components/form.js
> +                fields.map((item, index) => <TextField key={index} label={item.label} type={item.type} size={item.size}/>)
Во-первых, js в jsx пишется в фигурных кавычках. Это везде описано.
Во-вторых, что такое fields? У тебя это поле объекта data, поэтому здесь его так как ты делаешь не получить. Это же логично. Его ты можешь получить так - data.fields. Но зачем тебе объект, в котором одно поле? Сразу в data храни массив. В рендере не надо держать такой огромный кусок данных. Вынеси  его за пределы класса вверху. onBlur - это не данные, ты его должен передавать в компонент <TextField onBlur={this.handleBlur}/>

2017-06-26 10:02 UTC, AleksandrLv commented on src/Components/TextField.js
> +export default TextField
в конце пропущена точка с запятой

2017-06-26 10:02 UTC, AleksandrLv commented on src/Components/TextField.js
> +                />
Соблюдай правильное форматирование. Настрой eslint.
```
<input
    className="text-field__input"
    type={type}
    size={size}
    onBlur={this.handleBlur}
/>
```

2017-06-26 10:02 UTC, AleksandrLv commented on src/Components/form.js
> +                },
соблюдай правильное форматирование

2017-06-26 10:02 UTC, AleksandrLv commented on src/Components/form.js
> +export default Form
в конце пропущена точка с запятой

2017-06-27 19:00 UTC, nightingale69 commented on src/Components/TextField.js
> +export default TextField
Исправлено

2017-06-27 19:01 UTC, nightingale69 commented on src/Components/TextField.js
> +                />
Поменял на одиночные кавычки

2017-06-27 19:01 UTC, nightingale69 commented on src/Components/form.js
> +export default Form
Исправлено

2017-06-27 20:13 UTC, nightingale69 commented on src/Components/form.js
> +            surname: "",
Исправлено

2017-06-27 20:28 UTC, nightingale69 commented
По поводу компонента с маленькой буквы - я знаю, что нужно с большой буквы называть, но каждый раз, когда создаю новую ветку - опять название с маленькой буквы. Чтобы запустить вручную в директории переименовываю.

2017-06-27 20:44 UTC, nightingale69 commented on src/Components/form.js
> +                fields.map((item, index) => <TextField key={index} label={item.label} type={item.type} size={item.size}/>)
Исправил. Обработчик я написал один. Так надо делать?

2017-06-28 08:51 UTC, AleksandrLv requested changes
В чем проблема переименовать компонент и сделать коммит?

2017-06-28 08:51 UTC, AleksandrLv commented on src/Components/form.js
> +          onBlur={this.handleSurnameBlur}
Почему handleSurnameBlur? Это же должен быть один обработчик на все поля. Т.е. ты каким-нибудь образом должен идентифицировать то или иное поле, чтобы в обработчике ты понимал с каким полем работаешь

2017-06-29 20:33 UTC, nightingale69 commented on src/Components/form.js
> +          onBlur={this.handleSurnameBlur}
Я попытался идентифицировать каждое поле через лэйбл, но не знаю, как правильно записать в обработчике его

2017-06-29 20:34 UTC, nightingale69 commented
Переделал название компонента

2017-06-30 08:57 UTC, AleksandrLv requested changes

2017-06-30 08:57 UTC, AleksandrLv commented on src/Components/Form.js
> +          onBlur={this.handleFieldsBlur}
Ты тут обрабатываешь один филд, а не все сразу. handleFieldBlur

2017-06-30 08:57 UTC, AleksandrLv commented on src/Components/Form.js
> +          onBlur={this.handleFieldsBlur}
полей у TextField много. Поэтому лучше записать по другому
```
{fields.map((field, index) => (
    <TextField
        key={index}
        label={field.label}
        type={field.type}
        size={field.size}
        onBlur={this.handleFieldBlur}
    />
)}

2017-06-30 08:57 UTC, AleksandrLv commented on src/Components/Form.js
> +          onBlur={this.handleFieldsBlur}
Чтобы идентифицировать поле, можно добавить пропс id и потом его в компоненте TextField вместе с value передавать на верх

2017-07-03 19:57 UTC, nightingale69 commented on src/Components/Form.js
> +          onBlur={this.handleFieldsBlur}
Я сделал id, но как вывести в обработчик не понимаю. То, что я сейчас сделал в обработчике, как понял, сделал новую переменную с названием id, которая никак не относится к id в массиве. Выводится только в консоли undefined.

2017-07-15 20:02 UTC, AleksandrLv commented on src/Components/Form.js
> +			idField: value
Что ты здесь делаешь?

2017-07-15 20:04 UTC, AleksandrLv commented on src/Components/Form.js
> +		this.state = {};
this.state = {}; лишнее. Он автоматически создается. Следовательно и constructor не нужен в этом случае

2017-07-16 17:27 UTC, nightingale69 commented on src/Components/Form.js
> +			idField: value
Записываю в состояние каждый id со значением поля.

2017-07-16 17:27 UTC, nightingale69 commented on src/Components/Form.js
> +		this.state = {};
Я думал. что он необходим, даже без состояний, ведь я передавал состояние через обработчик handleFieldBlur.

2017-07-17 06:05 UTC, AleksandrLv commented on src/Components/Form.js
> +		});
ты уверен, что ты делаешь то, что ты хочешь? Тут написано - установи в state value в поле с названием idField.

2017-07-17 18:53 UTC, nightingale69 commented on src/Components/Form.js
> +		});
Если не нужен конструктор, ведь состояние создаётся автоматически, то получается, что и в хэндлере оно не нужно.

2017-07-19 15:21 UTC, AleksandrLv requested changes

2017-07-19 15:21 UTC, AleksandrLv commented on src/App.js
> +				<Form onBlur={this.handleFormField}/>
onBlur - странное название для этого метода, т.к. оно говорит что на форме происходит блюр, но блюр то на ней не происходит, блюр на инпутах. Лучше так onChange={this.handleFormChange}

2017-07-19 15:21 UTC, AleksandrLv commented on src/Components/Form.js
> +	};
Этот handle лишний

2017-07-19 15:21 UTC, AleksandrLv commented on src/Components/Form.js
> +						onBlur={this.handleFieldBlur}
onBlur={this.props.onBlur}

2017-07-19 18:15 UTC, nightingale69 commented on src/App.js
> +				<Form onBlur={this.handleFormField}/>
Исправил

2017-07-19 18:20 UTC, nightingale69 commented on src/Components/Form.js
> +	};
Убрал

2017-07-19 18:21 UTC, nightingale69 commented on src/Components/Form.js
> +						onBlur={this.handleFieldBlur}
Исправлено

2017-07-20 08:41 UTC, AleksandrLv approved these changes

2017-07-20 16:13 UTC, merged